schemas:
  bootstrap: 8000
  drudg8b3: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'public://favicon.ico'
  url: 'http://148.202.33.36:7914/sites/default/files/favicon.ico'
  use_default: 0
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: ''
  url: ''
  use_default: 0
table_responsive: '-1'
region_wells:
  liston: ''
  navigation: ''
  navigation_collapsible: ''
  header: ''
  precontent: ''
  precontent2: ''
  slideshow: ''
  precontent3: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
  content2: ''
  content3: ''
  content4: ''
  content5: ''
  content6: ''
  content7: ''
  content8: ''
  content9: ''
  content10: ''
  content11: ''
cdn_theme: bootstrap
cdn_cache_ttl_versions: -1
cdn_cache_ttl_themes: -1
reset_http_request_cache: ''
table: ''
fluid_container: 1
cdn_provider: custom
breadcrumb_home: 1
cdn_cache_ttl_assets: -1
cdn_cache_ttl_library: -1
